# 1.	Demonstrate three different methods for creating identical 2D arrays in NumPy. Provide the code for each method and the final output after each method

In [1]:
import numpy as np

In [2]:
'''1st method'''
np.array([[2,4], [6,8]])


array([[2, 4],
       [6, 8]])

In [3]:
'''2nd method'''
second_method = np.full((3,3),7)
second_method

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [4]:
'''3rd method'''
np.fromfunction(lambda x,y: x*y, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

# 2.	Using the NumPy function, generate an array of 100 evenly spaced numbers between 1 and 10 and Reshape that 1D array into a 2D array.

In [5]:
# Generate 100 evenly spaced numbers between 1 and 10
One_Dimension = np.linspace(1, 10, 100)
One_Dimension

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

In [6]:
# Reshape the 1D array into a 10x10 2D array
reshaped_array = One_Dimension.reshape(10, 10)

# Print the original and reshaped arrays
print("Original 1D array:")
print(One_Dimension[:10])  # Print only the first 10 elements for brevity
print()
print("Reshaped 2D array:")
print(reshaped_array)


Original 1D array:
[1.         1.09090909 1.18181818 1.27272727 1.36363636 1.45454545
 1.54545455 1.63636364 1.72727273 1.81818182]

Reshaped 2D array:
[[ 1.          1.09090909  1.18181818  1.27272727  1.36363636  1.45454545
   1.54545455  1.63636364  1.72727273  1.81818182]
 [ 1.90909091  2.          2.09090909  2.18181818  2.27272727  2.36363636
   2.45454545  2.54545455  2.63636364  2.72727273]
 [ 2.81818182  2.90909091  3.          3.09090909  3.18181818  3.27272727
   3.36363636  3.45454545  3.54545455  3.63636364]
 [ 3.72727273  3.81818182  3.90909091  4.          4.09090909  4.18181818
   4.27272727  4.36363636  4.45454545  4.54545455]
 [ 4.63636364  4.72727273  4.81818182  4.90909091  5.          5.09090909
   5.18181818  5.27272727  5.36363636  5.45454545]
 [ 5.54545455  5.63636364  5.72727273  5.81818182  5.90909091  6.
   6.09090909  6.18181818  6.27272727  6.36363636]
 [ 6.45454545  6.54545455  6.63636364  6.72727273  6.81818182  6.90909091
   7.          7.09090909  7.181

# 3a The difference in np.array, np.asarray and np.asanyarray.

In [7]:
'''
"np.array" convert the input into array whether it is in the array or not and when you explicitly want a new copy of the
data as a standard NumPy array.

"np.asarray" also convert the input into array whether it is in the array or not and when you want a NumPy array view of
the data if possible, while still allowing for a copy if needed. 

"np.asanyarray" when you specifically need to work with array-like objects or subclasses of ndarray without converting them
to standard ndarrays.

'''

'\n"np.array" convert the input into array whether it is in the array or not and when you explicitly want a new copy of the\ndata as a standard NumPy array.\n\n"np.asarray" also convert the input into array whether it is in the array or not and when you want a NumPy array view of\nthe data if possible, while still allowing for a copy if needed. \n\n"np.asanyarray" when you specifically need to work with array-like objects or subclasses of ndarray without converting them\nto standard ndarrays.\n\n'

# 3b The difference between Deep copy and shallow copy.

In [8]:
'''
"Deep Copy"
it is completely new and independent copy of the original object is created. This includes copying the values of
primitive data types and creating entirely new copies of any referenced compound objects within the original object. 
Modifications made to the copy will not affect the original object and vice versa, as they are separate objects in memory.

"Shallow Copy"
In a shallow copy, a new object is created with the same values as the original object for primitive data types.
However, for compound objects (like lists, dictionaries, classes), the references to the inner objects are simply copied.
This means both the original and the copy point to the same underlying data in memory.

'''

'\n"Deep Copy"\nit is completely new and independent copy of the original object is created. This includes copying the values of\nprimitive data types and creating entirely new copies of any referenced compound objects within the original object. \nModifications made to the copy will not affect the original object and vice versa, as they are separate objects in memory.\n\n"Shallow Copy"\nIn a shallow copy, a new object is created with the same values as the original object for primitive data types.\nHowever, for compound objects (like lists, dictionaries, classes), the references to the inner objects are simply copied.\nThis means both the original and the copy point to the same underlying data in memory.\n\n'

# 4. Generate a 3x3 array with random floating-point numbers between 5 and 20. Then, round each number in the array to 2 decimal places.

In [9]:
# Generate random floats between 5 and 20
random_array = np.random.rand(3, 3) * (20 - 5)

# Round to 2 decimal places
rounded_array = np.around(random_array, decimals=2)

# Print the original and rounded arrays
print("Original array:")
print(random_array)
print()
print("Rounded array:")
print(rounded_array)


Original array:
[[ 7.29114131 14.72275271  3.03228118]
 [ 6.38819972  0.82095369  7.44953433]
 [ 0.59198779  9.25964628  5.35058463]]

Rounded array:
[[ 7.29 14.72  3.03]
 [ 6.39  0.82  7.45]
 [ 0.59  9.26  5.35]]


# 5.	Create a NumPy array with random integers between 1 and 10 of shape (5, 6). After creating the array perform the following operations:
## 5a	Extract all even integers from array.

In [10]:
# Generate a 5x6 array of random integers between 1 and 10
New_array5x6 = np.random.randint(1, 11, size=(5, 6))

print(New_array5x6)


[[5 5 9 6 3 2]
 [1 6 1 3 5 5]
 [4 3 6 6 6 5]
 [9 7 6 7 8 1]
 [1 2 7 4 5 1]]


In [11]:
# Extract even integers
even_int = New_array5x6[New_array5x6 % 2 == 0]

print("Original array:")
print(New_array5x6)
print()
print("Even elements:")
print(even_int)

Original array:
[[5 5 9 6 3 2]
 [1 6 1 3 5 5]
 [4 3 6 6 6 5]
 [9 7 6 7 8 1]
 [1 2 7 4 5 1]]

Even elements:
[6 2 6 4 6 6 6 6 8 2 4]


## 5b	Extract all odd integers from array

In [12]:
# Extract odd integers
odd_int = New_array5x6[New_array5x6 % 2 != 0]

print("Original array:")
print(New_array5x6)
print()
print("odd elements:")
print(odd_int)

Original array:
[[5 5 9 6 3 2]
 [1 6 1 3 5 5]
 [4 3 6 6 6 5]
 [9 7 6 7 8 1]
 [1 2 7 4 5 1]]

odd elements:
[5 5 9 3 1 1 3 5 5 3 5 9 7 7 1 1 7 5 1]


# 6.	Create a 3D NumPy array of shape (3,3,3) containing random integers between 1 and 10. Perform the following operations:
## 6a Find the indices of the maximum values along each depth level (third axis).


In [13]:
# Generate random integers between 1 and 10.
array_3D = np.random.randint(1, 11, size=(3, 3, 3))

#Find the indices of the maximum values along each depth level (third axis)
max_indices = np.argmax(array_3D, axis=2)

# Print the original array and the indices of maximum values
print("Original array:")
print(array_3D)
print()
print("Indices of maximum values along depth level:")
print(max_indices)

Original array:
[[[ 7  2  8]
  [ 2 10  4]
  [ 7  5  3]]

 [[ 3  9  9]
  [10  9  5]
  [ 5  4  4]]

 [[ 6  3  4]
  [10  1  2]
  [ 2  9  3]]]

Indices of maximum values along depth level:
[[2 1 0]
 [1 0 0]
 [0 0 1]]


## 6b Perform element-wise multiplication of between both array.

In [14]:
# Element-wise multiplication
element_wise_multiply = array * array

# Print the original array and the product
print("Original array:")
print(array_3D)
print()
print("Element-wise multiplication:")
print(element_wise_multiply)

NameError: name 'array' is not defined

# 7.	Clean and transform the ‘Phone’ column in the sample dataset to remove non-numeric characters and convert it to a numeric data type. Also display the table attributes and data types of each column.

In [ ]:
import pandas as pd

In [ ]:
data = pd.read_csv('People Data.csv')

In [ ]:
# Remove all characters except digits, '-', and ' ' (space)
data['Phone'] = data['Phone'].str.replace(r"[^\d\- ]", "", regex=True)
print(data.info())

# 8.	Perform the following tasks using people dataset:
## 8a Read the ‘data.csv’ file using pandas, skipping the first 50 rows.


In [ ]:
data

In [ ]:
# Skipping the first 50 rows
df = pd.read_csv('People Data.csv', skiprows=50)

In [ ]:
df

## 8b Only read the columns: ‘Last Name’, ‘Gender’, ‘Email’, ‘Phone’ and ‘Salary’ from the file.

In [ ]:
new = data[['Last Name', 'Gender', 'Email', 'Phone', 'Salary']]
new

## 8c Display the first 10 rows of the filtered dataset.

In [ ]:
print(data.head(10))

## 8d Extract the ‘Salary’ column as a series and display its last 5 values.

In [ ]:
salary_series = data['Salary']
# Display the last 5 values
print(salary_series.tail(5))

# 9.	Filter and select rows from the People_Dataset, where the “Last Name' column contains the name 'Duke', 'Gender' column contains the word Female and ‘Salary’ should be less than 85000.

# 10.	Create a 7*5 Dataframe in Pandas using a series generated from 35 random integers between 1 to 6?

In [ ]:
# Generate 35 random integers between 1 and 6 (inclusive)
random_numbers = np.random.randint(1, 7, size=35)

# Create a Series from the random numbers
data_series = pd.Series(random_numbers)

# Reshape the Series into a 7x5 DataFrame
reshaped_df = data_series.values.reshape(7, 5)  # Use values attribute for NumPy array

# Create a DataFrame from the reshaped array (optional)
df = pd.DataFrame(reshaped_df)

# Print the DataFrame
print(df)

# 11.	Create two different Series, each of length 50, with the following criteria:
## 11a The first Series should contain random numbers ranging from 10 to 50.


## 11b The second Series should contain random numbers ranging from 100 to 1000.

## 11c Create a DataFrame by joining these Series by column, and, change the names of the columns to 'col1', 'col2', etc. 

# 12.	Perform the following operations using people data set:
## 12a Delete the 'Email', 'Phone', and 'Date of birth' columns from the dataset.


## 12b	Delete the rows containing any missing values.

## 12c Print the final output also. 

# 13.	Create two NumPy arrays, x and y, each containing 100 random float values between 0 and 1. Perform the following tasks using Matplotlib and NumPy:
## 13a Create a scatter plot using x and y, setting the color of the points to red and the marker style to 'o'.


## 13b Add a horizontal line at y = 0.5 using a dashed line style and label it as 'y = 0.5'. 

## 13c Add a vertical line at x = 0.5 using a dotted line style and label it as 'x = 0.5'.

## 13d Label the x-axis as 'X-axis' and the y-axis as 'Y-axis'.

## 13e Set the title of the plot as 'Advanced Scatter Plot of Random Values'.

## 13f Display a legend for the scatter plot, the horizontal line, and the vertical line. 

# 14.	Create a time-series dataset in a Pandas DataFrame with columns: 'Date', 'Temperature', 'Humidity' and Perform the following tasks using Matplotlib: 
## 14a Plot the 'Temperature' and 'Humidity' on the same plot with different y-axes (left y-axis for 'Temperature' and right y-axis for 'Humidity').


## 14b Label the x-axis as 'Date'.

## 14c Set the title of the plot as 'Temperature and Humidity Over Time'. 

# 15.	Create a NumPy array data containing 1000 samples from a normal distribution. Perform the following tasks using Matplotlib:
## 15a Plot a histogram of the data with 30 bins.

## 15b Overlay a line plot representing the normal distribution's probability density function (PDF). 

## 15c Label the x-axis as 'Value' and the y-axis as 'Frequency/Probability'. 

## 15d Set the title of the plot as 'Histogram with PDF Overlay'. 

# 16 Set the title of the plot as 'Histogram with PDF Overlay'.

In [ ]:
import matplotlib.pyplot as plt

# histogram and PDF overlay)

# Set the plot title
plt.title('Histogram with PDF Overlay')

# Display the plot
plt.show()

# 17.	Create a Seaborn scatter plot of two random arrays, color points based on their position relative to the origin (quadrants), add a legend, label the axes, and set the title as 'Quadrant-wise Scatter Plot'.

In [ ]:
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt  # Needed for legend

# Generate random arrays
np.random.seed(10)  # Set a seed for reproducibility
x = np.random.randn(100)  # 100 random values from a standard normal distribution
y = np.random.randn(100)

# Define a function to determine quadrants based on origin
def get_quadrant(x, y):
  if x > 0 and y > 0:
    return "Upper Right"
  elif x < 0 and y > 0:
    return "Upper Left"
  elif x < 0 and y < 0:
    return "Lower Left"
  else:
    return "Lower Right"

# Create a new array for quadrant labels
quadrants = [get_quadrant(i, j) for i, j in zip(x, y)]

# Create the scatter plot with quadrant coloring and legend
sns.scatterplot(x=x, y=y, hue=quadrants, palette="Set3")
plt.legend(title="Quadrant")  # Add legend with title

# Label axes and set title
plt.xlabel("X-axis")
plt.ylabel("Y-axis")
plt.title("Quadrant-wise Scatter Plot")

# Display the plot
plt.show()

# 18.	With Bokeh, plot a line chart of a sine wave function, add grid lines, label the axes, and set the title as 'Sine Wave Function'.

# 19.	Using Bokeh, generate a bar chart of randomly generated categorical data, color bars based on their values, add hover tooltips to display exact values, label the axes, and set the title as 'Random Categorical Bar Chart'.

# 20.	Using Plotly, create a basic line plot of a randomly generated dataset, label the axes, and set the title as 'Simple Line Plot'.

# 21.	Using Plotly, create an interactive pie chart of randomly generated data, add labels and percentages, set the title as 'Interactive Pie Chart'.